services:
  client:
    build:
      context: .
      dockerfile: ./docker/client.Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - server
    volumes:
      - ./packages/client:/app/packages/client
      - ./packages/shared:/app/packages/shared

  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    volumes:
      - ./packages/server:/app/packages/server
      - ./packages/shared:/app/packages/shared
    ports:
      - "5000:5000"
      - "6499:6499"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
